sudo: required
language: bash
services: docker

env:
  global:
  - DOCKER_IMAGE=nginx-rtmp

jobs:
  include:
  - arch: amd64
    env: DOCKER_FILE=Dockerfile
  - arch: arm64
    env: DOCKER_FILE=Dockerfile_arm64

script:
  - echo ${DOCKER_FILE}
  - docker build -t ${DOCKER_IMAGE} . --file ${DOCKER_FILE}
after_script:
  - docker images
  - docker run -d -p 1935:1935 -p 8080:80 -t ${DOCKER_IMAGE}
  - docker ps -a
